# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(456, 411)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 421, 351))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.post1 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.post1.setObjectName("post1")
        self.gridLayout.addWidget(self.post1, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.post2 = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.post2.setObjectName("post2")
        self.gridLayout.addWidget(self.post2, 4, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 2, 1, 1)
        self.id = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.id.setObjectName("id")
        self.gridLayout.addWidget(self.id, 3, 1, 1, 3)
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 0, 1, 4)
        self.birth = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.birth.setObjectName("birth")
        self.gridLayout.addWidget(self.birth, 2, 1, 1, 3)
        self.name = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 3)
        self.surname = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.surname.setObjectName("surname")
        self.gridLayout.addWidget(self.surname, 1, 1, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Imie:"))
        self.label_5.setText(_translate("Dialog", "Adres pocztowy:"))
        self.label_2.setText(_translate("Dialog", "Nazwisko:"))
        self.label_4.setText(_translate("Dialog", "Pesel:"))
        self.label_3.setText(_translate("Dialog", "Data Urodzenia:"))
        self.label_6.setText(_translate("Dialog", "Miejscowość:"))
        self.pushButton.setText(_translate("Dialog", "Ok"))
